docker:
  - image: cibuilds/github:0.10
steps:
  - slack/notify:
      channel: circleci
      color: '#42e2f4'
      mentions: 'tatman'
      message: "publishing new release on github for $CIRCLE_PROJECT_REPONAME"
      webhook: webhook
  - attach_workspace:
      at: ~/ircWebBot
  - run:
      name: "Publish Release on GitHub"
      working_directory: ~/ircWebBot
      command: |
        VERSION=$(cat version)
        ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build/libs/ircWebBot-*.jar
